# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/urfave/cli";
    fetch = {
      type = "git";
      url = "https://github.com/urfave/cli";
      rev = "0bdeddeeb0f650497d603c4ad7b20cfe685682f6";
      sha256 = "1ny63c7bfwfrsp7vfkvb4i0xhq4v7yxqnwxa52y4xlfxs4r6v6fg";
    };
  }
  {
    goPackagePath = "github.com/gorilla/mux";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/mux";
      rev = "757bef944d0f21880861c2dd9c871ca543023cba";
      sha256 = "0c8ms7bwj9vnvcmm3ksrm3vbfdd46chl1350drzcg7y6pa6hxx88";
    };
  }
  {
    goPackagePath = "github.com/gorilla/websocket";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/websocket";
      rev = "5ddbd28fbd5a0179960f2bcaa989e0925356dc7f";
      sha256 = "1x7djdfp1x72hmah79w5c0drb6285hmj9ffj631nrz7l60542j6x";
    };
  }
  {
    goPackagePath = "github.com/russolsen/transit";
    fetch = {
      type = "git";
      url = "https://github.com/russolsen/transit";
      rev = "af303642df6a22c0e4d39b79daacdb88df12a2c7";
      sha256 = "0w0ckcadiky7mf2x5bncy1k2l6p4va4z39r58kjqwdini5922n5v";
    };
  }
  {
    goPackagePath = "github.com/pborman/uuid";
    fetch = {
      type = "git";
      url = "https://github.com/pborman/uuid";
      rev = "1b00554d822231195d1babd97ff4a781231955c9";
      sha256 = "0rjkcf85sagdwzsycj1bbjyx5bgmrc1i8l5qf1f44z24rhbbkaan";
    };
  }
  {
    goPackagePath = "github.com/shopspring/decimal";
    fetch = {
      type = "git";
      url = "https://github.com/shopspring/decimal";
      rev = "ea75adedfea8d902939c65b210dd1854f69dd1dd";
      sha256 = "1nprlwfwikl8kzz29vcsw2xsgz8sgzrsxv8f5lx8m7gyxwphyk3a";
    };
  }
  {
    goPackagePath = "github.com/kr/pty";
    fetch = {
      type = "git";
      url = "https://github.com/kr/pty";
      rev = "ce7fa45920dc37a92de8377972e52bc55ffa8d57";
      sha256 = "0mdlr2mmwjznw2id0l4200xjajq9dh1kxn3z7d3ksn0b5fwinzmk";
    };
  }
  {
    goPackagePath = "github.com/docker/docker";
    fetch = {
      type = "git";
      url = "https://github.com/docker/docker";
      rev = "092cba3727bb9b4a2f0e922cd6c0f93ea270e363";
      sha256 = "0l9kjibnpwcgk844sibxk9ppyqniw9r0np1mzp95f8f461jb0iar";
    };
  }
  {
    goPackagePath = "github.com/neelance/graphql-go";
    fetch = {
      type = "git";
      url = "https://github.com/neelance/graphql-go";
      rev = "5b2978fcb1baf5d104a51d2638e2204abac0f5fd";
      sha256 = "1wi2kgmnq8cgic5h2d305na1cv8qk3xcqppgqi86pwyzz1j6007g";
    };
  }
  {
    goPackagePath = "github.com/opentracing/opentracing-go";
    fetch = {
      type = "git";
      url = "https://github.com/opentracing/opentracing-go";
      rev = "6edb48674bd9467b8e91fda004f2bd7202d60ce4";
      sha256 = "0kwighhdm187b1yzcccm4hpy7m5sv1dij5ckg31n2614xvpippby";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "236b8f043b920452504e263bc21d354427127473";
      sha256 = "0hrhkm63kq4x35318ljpj3yy4w33kcqaq59xvzrrfqga7p1xvz8j";
    };
  }
]
